---
title: "INFO500 Final Project"
author: "Ziyin Tang"
date: "`r format(Sys.Date(), '%Y-%m-%d')`"
output: html_document 
---

<!--  
   suppresses all code chunks from appearing
-->

```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
```

<!--
   You should change the working directory in the folder (here, "project_data") which contains the data.txt
-->

```{r, readin}
metdata <- read.table('data.txt',header=T)
met_intensity<-metdata[4:53]
```


### Basic description of the dataset

1. There are `r nrow(metdata)` observations in this dataset.

2. There are `r ncol(met_intensity)` metabolic features totally.

```{r, summary}
# create a descriptive table for age and exposure variable
Age <- round(summary(metdata$age),digit=1)
Exposure <- round(summary(metdata$exposure),digit=1)
summary <- rbind(Age,Exposure)
row.names(summary) <- c("Age", "Exposure" )
knitr::kable(summary, caption =  "Table 1. Summary for age and exposure variable")
```


```{r, dataclean}
# Calculate the number of samples detected each of metabolic features
total_notmissing<-apply(met_intensity,2,function(x){return(length(which(!is.na(x))))})

# Remove metabolic features if signal is not detected in at least 10% of all samples
good_features<-which(total_notmissing>0.1*dim(metdata[1])) 
final_met_int<-met_intensity[ ,good_features]

# final dataset
basic<-cbind(metdata[1:3],metdata[54:56])
final_data<-cbind(basic,final_met_int)
```


### Data cleaning

1. After removing metabolic features which are not detected in at least 10% of all samples, there are totally `r ncol(final_met_int)` metabolic features.


<!--

Grades for students' participation:
  Weijia Qian -- 1
  Wenlu Ye -- 1
  Courtney Gale -- 1
  
-->